### ISSUE TITLE
getting error when trying to login in one node  with latest version install. although it is working with other nodes

### ISSUE THREAD

**Issue by ankur8** [mohatb/kubectl-exec#10]
creating pod "aks-xlcompute-11385793-vmss00001x-exec-17300" on node "aks-xlcompute-11385793-vmss00001x"
pod "aks-xlcompute-11385793-vmss00001x-exec-17300" deleted
Error from server (BadRequest): container "nsenter" in pod "aks-xlcompute-11385793-vmss00001x-exec-17300" is not available

**Comment by mohatb** [comment]
@ankur8 Can you run any privileged pod on that node?
