### ISSUE TITLE
this will not work if nodes have taints attached

### ISSUE THREAD

**Issue by ankur8** [mohatb/kubectl-exec#3]
It is failing on nodes with taints attached any solution

**Comment by mohatb** [comment]
@ankur8 yes, are you referring to NoSchedule taint effect on the node ? if yes, then this is normal as the tool creates a pod with a nodeselector  on that node. for it to work, it has to be able to create pods on that node.

**Comment by ankur8** [comment]
can this kubectl-exec support this i.e to add toleration in cli

**Comment by ankur8** [comment]
i solved it by adding overides for pod spec thanks!
