### ISSUE TITLE
kubectl --generator is removed from kubectl 1.21

### ISSUE THREAD

**Issue by timo-haas-by** [mohatb/kubectl-exec#4]
Support for --generator was dropped in the latest release of kubectl 1.21.
It was already marked as deprecated.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#deprecation

**Comment by mohatb** [comment]
This has been resolved here https://github.com/mohatb/kubectl-exec/pull/5
