### ISSUE TITLE
mount option didn't attach to shell

### ISSUE THREAD

**Issue by rickyzhang82** [mohatb/kubectl-exec#7]
Is it missing `-ti`?

https://github.com/mohatb/kubectl-exec/blob/1bfe7115f72b54fec4f77a6023084830d69e4f36/kubectl-exec#L200-L202

**Comment by mohatb** [comment]
no, since this is under the mount option it creates a pod and mounts the root "/" to "/host" on the pod. the purpose of having this without "ti" is that you can use kubectl cp without opening another terminal. the other exec pods are removed after you leave the terminal but mount pods should be manually deleted. will add some extra help messages and documentation on the function.

**Comment by mohatb** [comment]
I've updated the script so we no longer interact with the pod itself or create mounts. the pod will directly access the node, this way we can copy data from/to node by only specifying the pod name. For example:

```
From Local -> Node:
kubectl cp /etc/hostname default/minikube-hostpath-mount:/tmp/hostname

From Node -> Local
kubectl cp default/minikube-hostpath-mount:/etc/hostname /tmp/hostname
```

**Comment by rickyzhang82** [comment]
I thought I could `chroot /host` after attach an interactive shell.

To simplify the script, we remove the mount options and just mount node root fs in /host.

To debug k8s, I will run `journalctl` to check kublet log. It requires an interactive shell. Anyway, it is up to you. I will do that in my forked.

thanks!

**Comment by mohatb** [comment]
using that method it works when transferring from node -> local but not from local -> node as after that I found the files exist only on the pod not the node. feel free to submit a PR with your implementation and I can review it.

**Comment by rickyzhang82** [comment]
Well, it is not a big deal. Once you launched a pod with a mount to node rootfs, you could do `kubectl cp` outside the pod in any direction.

I believe your mount option is redundant. You already chroot and mount node rootfs in the default.
